version: "3"
services:
  postgres:
    image: "postgres:13.4-alpine"
    container_name: "management-hub-postgres"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "./db/init.sql:/docker-entrypoint-db.d/1-init.sql"
    ports:
      - "35432:5432"
