server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: "e2b2be9462f45a280533"
            client-secret: "b9b42d39853952dc129f881be5461714d743bdef"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port: 36379

feign:
  client:
    config:
      user:
        connect-timeout: 50000
        read-timeout: 30000
        request-interceptors:
          - com.example.apigateway.client.interceptor.CorrelationIdInterceptor
      organization:
        connect-timeout: 50000
        read-timeout: 30000
        request-interceptors:
          - com.example.apigateway.client.interceptor.CorrelationIdInterceptor
      github-service:
        connect-timeout: 50000
        read-timeout: 30000
        request-interceptors:
          - com.example.apigateway.client.interceptor.CorrelationIdInterceptor

security:
  secret: "SECRET"
  session-duration-minutes: 86400
  success-redirect-url: "http://localhost:3000/dashboard"
  allowed-origin: "http://localhost:3000"

services:
  user:
    url: 'http://localhost:8081'
  github:
    url: 'http://localhost:9090'

csrf:
  xsrf_cookie_name: 'MH-XSRF'
  xsrf_header_name: "MH-X-XSRF"
  cookie_domain: "localhost"

rate-limiter:
  max-requests: 10000

