server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: "e2b2be9462f45a280533"
            client-secret: "b9b42d39853952dc129f881be5461714d743bdef"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

