server:
  port: 9090
spring:
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:35432/postgres
token:
  return-length: 5
